### ISSUE TITLE
Please update dependencies

### ISSUE THREAD

**Issue by WebReflection** [nebrius/raspi-serial#10]
I could as well file a MR but I'd like to touch-base first: the current version of serialport doesn't build anymore in latest ArchLinux for Raspberry Pi 4, while version 8 works without issues.

This is indirectly affecting the installation of raspi-io, as this module is a dependency.

Thanks for considering an upgrade, or for any sort of outcome.

**Comment by WebReflection** [comment]
FYI, it looks like the issue with serialport 7 is with NodeJS 13, as version 12 builds just fine.

**Comment by nebrius** [comment]
Thanks for letting me know. I just published v6.0.0 of raspi-serial to npm with serialport v8. The breaking change is that I dropped support for EOLed versions of Node.js FYI
