### ISSUE TITLE
Error: Invalid parity setting 5

### ISSUE THREAD

**Issue by SaekiRaku** [nebrius/raspi-serial#12]
Hi, I'm using `Raspberry Pi Zero W` with `Raspberry Pi OS (32-bit) Lite`, and running on `NodeJS v11.0.0`.

Here is my code:

```javascript
import { init } from "raspi";
import { Serial, PARITY_SPACE } from "raspi-serial";

init(()=>{
  var serial = new Serial({
        portId: "/dev/ttyAMA0",
        parity: PARITY_SPACE
    });
});
```

And the error log is:  `(node:742) UnhandledPromiseRejectionWarning: Error: Invalid parity setting 5`.

If not setting the parity property, it will have no error output.

**Comment by nebrius** [comment]
That's...really strange. Is there any way you can get a full stack trace? `PARITY_SPACE` has a value of `space`, not `5`, and that exception message isn't being thrown by `raspi-serial`. I'm guessing there's something going on under the hood in the serialport module.

**Comment by SaekiRaku** [comment]
Here is the whole script and output:

```javascript
// index.js
import { init } from "raspi";
import { Serial, PARITY_SPACE } from "raspi-serial";

init(() => {
    console.log(PARITY_SPACE, typeof PARITY_SPACE);

    var serial = new Serial({
        portId: "/dev/ttyAMA0",
        parity: PARITY_SPACE
    });

    serial.open(() => { });
});
```

```
# node -r esm index.js
space string
(node:880) UnhandledPromiseRejectionWarning: Error: Invalid parity setting 5
(node:880) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:880) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nebrius** [comment]
Ah, I figured it out. The Raspberry Pi Zero W (and Pi 1, 2, and Zero) don't support space parity, sorry. They only support even, odd, stick, or no parity.

**Comment by SaekiRaku** [comment]
@nebrius I see, thanks for your reply!
