### ISSUE TITLE
Is it possible to .off listeners?

### ISSUE THREAD

**Issue by danieltroger** [nebrius/raspi-serial#14]
I do this:
```
serial.on('data', callback);
```
But very often.
  
So what happens if I have .on'd a million functions and only the last one actually does something? It feels like it would lead to bad performance. So is it possible to remove an "event listener" again?

I don't think this is developed on anymore so I'll just build a stack of promises where I resolve the last one everytime data comes and if I need to wait for data I'll wait for my promise instead, but .off would have been nice.

**Comment by nebrius** [comment]
Yeah, I'm not actively working on this project anymore. Feel free to send a PR adding an `off` method and I'll review it though.

**Comment by danieltroger** [comment]
Where is the .on function defined?

**Comment by nebrius** [comment]
I'll be honest, I haven't worked on this code in a long time and don't really remember.

**Comment by danieltroger** [comment]
:(

I searched https://github.com/nebrius/raspi and https://github.com/nebrius/raspi-serial and couldn't find it

**Comment by nebrius** [comment]
Sorry, I can't really help out much
