### ISSUE TITLE
Develop on non RPi -> npm install error: The CPU architecture "x64" is incompatible with this module.

### ISSUE THREAD

**Issue by pingustar** [nebrius/raspi-serial#15]
How install and develop on non Raspberry Pi environment?

I was expecting to be able to develop on my Mac and commit the code to GitHub, so I only have to clone the repo and deploy on my Raspberry Pi.

How do you guys do this?

**Comment by nebrius** [comment]
You can try installing the dependency with `npm install --force` to get around the platform check. Some of the raspi-* modules still fail to install when doing this, but IIRC raspi-serial should be fine.

FWIW I clone the repo, install dependencies, etc. on an RPi and then [configure VS Code](https://code.visualstudio.com/docs/remote/remote-overview) on my laptop to remotely connect to it for my dev work.

**Comment by pingustar** [comment]
> You can try installing the dependency with `npm install --force` to get around the platform check. Some of the raspi-* modules still fail to install when doing this, but IIRC raspi-serial should be fine.
> 
> FWIW I clone the repo, install dependencies, etc. on an RPi and then [configure VS Code](https://code.visualstudio.com/docs/remote/remote-overview) on my laptop to remotely connect to it for my dev work.

thanks for your reply, unfortunately `yarn install --force` doesnt want to work, same error. 

A remote VS Code connection is unfortunately not possible in my scenario, any other ideas for a workaround?

**Comment by nebrius** [comment]
No. Those are the only two options I'm aware of. Can you use npm instead of yarn?

**Comment by pingustar** [comment]
> No. Those are the only two options I'm aware of. Can you use npm instead of yarn?

same with npm.

May I ask a different question though, how would you convert the HEX Buffer data to string/ASCII?

**Comment by nebrius** [comment]
> > No. Those are the only two options I'm aware of. Can you use npm instead of yarn?
> 
> same with npm.

Unfortunately I'd say it's not possible then.
 
> May I ask a different question though, how would you convert the HEX Buffer data to string/ASCII?

Take a look at the [Buffer](https://nodejs.org/api/buffer.html) class, specifically the [toString](https://nodejs.org/api/buffer.html#buftostringencoding-start-end) method.

**Comment by pingustar** [comment]
Thanks, appreciate your help!
