### ISSUE TITLE
Find solution to BLE-UART conflict on the RPi3

### ISSUE THREAD

**Issue by nebrius** [nebrius/raspi-serial#3]
The bluetooth chip on the RPi 3 uses serial to communicate, which disables it for general use. We should figure out a way to disable bluetooth so it can be used for serial again. Possible idea: https://www.abelectronics.co.uk/kb/article/1035/raspberry-pi-3-serial-port-usage

**Comment by don** [comment]
/dev/ttyAMA0 is mapped to Bluetooth on the Raspberry Pi 3

raspi-serial breaks Bluetooth (e.g. mixing [Johnny-Five](https://github.com/rwaldron/johnny-five) and [bleno](https://github.com/sandeepmistry/bleno)) unless the DEFAULT_PORT is changed from /dev/ttyAMA0 to /dev/ttyS0

https://github.com/nebrius/raspi-serial/blob/823eb9470c393a6e7487fe9c3bedc12a35302dc1/dist/index.js#L37

**Comment by nebrius** [comment]
Thanks for the update @don!

**Comment by nebrius** [comment]
Thinking about it (after being pinged), for the time being I'm going to disable serial support on the RPi3.

About getting serial to work on the RPi 3: In the past, I've leaned towards making things automatic, e.g. raspi-io configures the Pi to do everything it needs without user intervention. Normally this doesn't have any negative effects, but I fear that if I were to automatically disable bluetooth that it would catch users by surprise. I'm starting to wonder if I should create some sort of question-answer flow for people installing Raspi-IO, which explicitly asks the user these questions to be run on post-install of raspi-io...

🤔

**Comment by nebrius** [comment]
I just published v7.3.0 of raspi-io, which now disables serial support in Raspi IO on the RPi 3, and I included steps on how to enable it in the wiki

**Comment by nebrius** [comment]
I'm going to close this, as we have a workable solution now.
