### ISSUE TITLE
wrong work event

### ISSUE THREAD

**Issue by your-comrade** [nebrius/raspi-serial#6]
When I connect RX and TX pins on my Raspberry Pi model B+ V1.2 and use default example I can't recieve the data which I sent.

**Comment by nebrius** [comment]
To clarify so I can make sure I'm understanding you properly, did you connect pin `P1-8` to pin `P1-10` on a single Raspberry Pi, and you ran this program on that same Raspberry Pi?

```JavaScript
const raspi = require('raspi');
const Serial = require('raspi-serial').Serial;

raspi.init(() => {
  var serial = new Serial();
  serial.open(() => {
    serial.write('Hello from raspi-serial');
    serial.on('data', (data) => {
      process.stdout.write(data);
    });
  });
});
```

**Comment by your-comrade** [comment]
yes

**Comment by nebrius** [comment]
Ack, I'm really sorry. I thought I posted this already two weeks ago, but just now saw I never actually clicked the `Comment` button.

Original post: @SntMichael I just tested on my own device and it works fine. Let's check a couple of other things:

- Can you make sure you followed all of the instructions at https://github.com/nebrius/raspi-serial#installation? There are several manual steps that have to be taken to get serial to work properly.
- Which version of Raspbian are you running, and which version of Node.js are you running?
- Can you triple check your wiring? The loopback wiring pins should be connected to the 4th and 5th pins from the left on the outer row of pins.

**Comment by your-comrade** [comment]
I found what the problem was. I try to do it on Raspberry Pi 3 B and it works. Maybe it's connected with installation new raspbian on my old board that already not supported this OS.
