### ISSUE TITLE
raspi.init() functionality

### ISSUE THREAD

**Issue by cakiray** [nebrius/raspi-serial#7]
What does raspi.init() do actually? I cannot write and read data out of raspi.init() block. How can I do without this function? I want to call read and send functions in various functions.

And there is a issue with on(). My code enters write() functions but doesnt on(). What may cause this?
Thanks.

**Comment by nebrius** [comment]
Can you post a code snippet showing how you're using `on` and `write`? I'd be very surprised if `raspi.init` is the culprit because it doesn't do anything (anymore). It's there for backwards compatibility, [but only consists of of this TypeScript code](https://github.com/nebrius/raspi/blob/master/src/index.ts#L29-L31):

```TypeScript
export function init(cb: () => void): void {
  process.nextTick(cb);
}
```

**Comment by cakiray** [comment]
I am writing in nodejs. Then I can delete raspi.init() function since it does nothing. Right?
`port.open(() => {
       port.on('data', (data) => {
             consolo.log('OPENED');
      )};
)};`

I wrote on() function as above. But it does not enter on() anyway. It enters open() but not on(). I couldnt understand why because the code is the same that the code provided as example, isnt it?
Thank you.

**Comment by nebrius** [comment]
Technically speaking, you _can_ delete `raspi-init`, but I wouldn't recommend it. I'm 99% certain it will _not_ fix your problem, and I may add code back to it without warning, which would break your app without warning.

Looking at your code, it would appear that your Raspberry Pi isn't receiving data from the serial device you connected to it. Can you answer these questions for me:

1. What serial device did you connect to the Raspberry Pi?
1. Can you double check that you connected the TX pin of your serial device to the RX pin on the Raspberry Pi?
1. Can you double check that you supplied the correct baud rate for this device to `new Serial({ baudrate: ### });`. If you entered an incorrect baudrate, the Raspberry Pi may not be able to read and data, even garbled.
1. Can you double check that the serial device you connected is a 3.3v device? If it's a 5v device, you will need to use a level translator in between.
1. Can you verify that you followed all of the steps in https://github.com/nebrius/raspi-serial#installation correctly?

EDIT: I realize some of these can be confusing questions if you're new to hardware, so let me know if you're not sure what some of them mean and I'll give some background context.

**Comment by nebrius** [comment]
I'm going to go ahead and close this issue due to inactivity. If you still need help, feel free to reopen it.
