### ISSUE TITLE
I have encountered some errors: npm ERR! Error: Method Not Allowed, npm ERR! code E405

### ISSUE THREAD

**Issue by Laquio** [nebrius/raspi-serial#8]
See below:

root@AIMPI:/var/aim# npm install raspi
(node:760) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm WARN package.json aim-mikronode-ng@1.0.0 No README data
npm WARN package.json connect-flash@0.1.1 No license field.
npm WARN package.json ntp-client@0.5.3 No license field.
npm WARN package.json spi@0.2.0 No license field.
raspi@5.0.2 node_modules/raspi

root@AIMPI:/var/aim# npm install raspi-serial
(node:743) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm WARN package.json spi@0.2.0 No license field.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.62-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "raspi-serial"
npm ERR! cwd /var/aim
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/aim/npm-debug.log
npm ERR! not ok code 0
root@AIMPI:/var/aim#

![image](https://user-images.githubusercontent.com/7693181/45029897-b857df80-b07c-11e8-925b-737788924118.png)

root@AIMPI:/var/aim# cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by goseese** [comment]
I am having a similar issue attempting to install raspi-serial on a Raspberry Pi 3 B+

```
666 error Error: Method Not Allowed
666 error     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
666 error     at /usr/share/npm/lib/cache/add-named.js:203:12
666 error     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
666 error     at FSReqWrap.oncomplete (fs.js:135:15)
667 error If you need help, you may report this *entire* log,
667 error including the npm and node versions, at:
667 error     <http://github.com/npm/npm/issues>
668 error System Linux 4.14.62-v7+
669 error command "/usr/bin/node" "/usr/bin/npm" "install" "raspi-serial"
670 error cwd /var/www
671 error node -v v8.11.1
672 error npm -v 1.4.21
673 error code E405
674 verbose exit [ 1, true ]
```

OS
```
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch
```

**Comment by nebrius** [comment]
Ah, I see the issue. "Method Not Allowed" is a 405 HTTP error. You're both using a version of npm that's been deprecated and the npm service no longer supports (I recommend at _least_ version 5.x.x of npm).

You'll need to upgrade to the latest version of npm with `sudo npm install -g npm` to fix it. If that doesn't work, you may need to update npm manually.

**Comment by goseese** [comment]
That was it thank you for your help. I realize this is not really related to the module, but I appreciate your ability to help out regardless.

**Comment by nebrius** [comment]
I'm glad you got it working!

**Comment by vedhaperi** [comment]
I faced this error bc npm install was pointing to a registry that was not there. You could update the registry in this way:
`npm config set registry https://registry.your-registry.npme.io/`
Or in general you can set it to:
`npm config set registry https://registry.npmjs.org`

**Comment by nebrius** [comment]
Thanks for the tip @vedhaperi!

**Comment by ali3bdalla** [comment]
I got the same issue in my aws 

actuly Iam not able even to install node js on my server

**Comment by nebrius** [comment]
@3li3bdalla you'll need to get node.js installed before you can use this module. I would also note that this module can _only_ be used on a Raspberry Pi, and won't work on most servers.

**Comment by ali3bdalla** [comment]
@nebrius  thanks very match it is work for me after i made some google about how to install node js on centos aws

**Comment by elucidsoft** [comment]
I got this error because I setup a new dev machine and my git config --global user.email and --global user.name were empty.
