### ISSUE TITLE
Sample code exits after first byte received

### ISSUE THREAD

**Issue by dbrooks75** [nebrius/raspi-serial#9]
When I use the basic sample code provided, I am able to connect with putty running on Windows 10.  The write works.  But as soon as I type one letter in putty, it is output on the pi, but then the program ends.  I expected the serial.open to be similar to http.listen.

**Comment by nebrius** [comment]
Hi @dbrooks75. When you say you're using PuTTY, are you connecting to the Raspberry Pi using SSH over the network, or are you connecting via TTY over serial?

Can you clarify what you mean when you say that serial.open acts differently than http.listen? They should behave the same.

**Comment by dbrooks75** [comment]
I use TTY over serial, in my specific case it's COM3.  I know I have the connection parameters correct because the on-data trigger fires and the handler outputs the character on the pi terminal.  But then the program ends without error after outputting the first character.  I would think the on-data handler would continue listening after the first character.  That's why I mentioned http.listen, which keeps listening after the first http request.

**Comment by nebrius** [comment]
I hate to break it to you, but what you're trying to do isn't possible. If you want to control a serial peripheral from the Raspberry Pi _and_ connect to the serial TTY at the same time, you need two serial ports.

Serial ports are different from HTTP connections in that HTTP connections have the concept of a software port (443 for TLS, 22 for SSH, etc.) _and_ the concept of a connection (which, technically is the combination of source IP address and destination TCP/UDP/etc. port). The HTTP protocol is aware of all of these pieces of information, which allows multiple connections to be multiplexed over a single Ethernet or WiFi peripheral. RS-232 doesn't have a protocol though of any significance, just a start bit, stop bit, and parity bits (RS-232 is the spec for serial ports). Thus, serial has no way to multiplex multiple connections over a single serial peripheral like HTTP does.

In RS-232, if you want to support multiple connections, you need multiple RS-232 peripherals (e.g. on different pins). The Raspberry Pi only has one port (in practice).

**Comment by dbrooks75** [comment]
ok, thanks for the feedback.
